global_coordinates:
  altitude: 90.0
  latitude: -29.78634556614431
  longitude: -51.16386383414946
px4_dir: ~/PX4-Autopilot
px4_default_airframe: gazebo-classic_iris # Change to 'iris' if using PX4 version lower than v1.14